; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.0"

; Modules
projects[ctools][subdir] = "sites/all/modules/contrib/ctools"
projects[ctools][version] = "1.0-alpha4"

projects[devel][subdir] = "sites/all/modules/contrib/devel"
projects[devel][version] = "1.0"

projects[environment_indicator][subdir] = "sites/all/modules/contrib/environment_indicator"
projects[environment_indicator][version] = "1.0-alpha1"

projects[views][subdir] = "sites/all/modules/contrib/views"
projects[views][version] = "3.0-beta3"

